config/routes.rb
Rails.application.routes.draw do
  devise_for :users  

  namespace :api, defaults: {format: :json} do
    devise_scope :user do
      resource :session, only: [:create, :destroy]
    end
    
  end

  root :to => "home#index"

  get '/dashboard' => 'templates#index'
  get '/task_lists/:id' => 'templates#index'
  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  namespace :api do
    scope :app, module: 'app' do
      get  :api1  # get list task
      get  :api2
      post :api3
      post :api4
      post :api5
      post :api6
    end

  end
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
	belongs_to :owner, class_name: User
  has_many :tasks, -> { order :priority }, foreign_key: :list_id, dependent: :destroy

  validates :owner, presence: true
  validates :name, presence: true
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_list_params
      params[:task_list]
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<%= form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task list', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form' %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>